name: .NET Core

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies for all projects
      run: dotnet restore
      
    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
      

    - name: Upload a build artifact for the Bicep template
      uses: actions/upload-artifact@v2.1.3
      with:
        name: bicep-template
        path: deploy.bicep
        if-no-files-found: error   
        
  release-to-dev:
    runs-on: ubuntu-latest
    
    needs: [ build ]
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: drop
        path: ./taa-portal/
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: AnimalAdoptionApp
        publish-profile: ${{ secrets.AnimalAdoptionAppPublishSettings }}
        package: ./taa-portal/

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AnimalAdoptionServicePrincipal }}
        
    - name: Get Secrets from Test Key Vault
      id: getSecretsFromTestKeyVault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: AnimalAdoptionKeyVault
        secrets: 'GlobalPassword, SimulatedFailureChance'

    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: AnimalAdoptionApp
        #app-settings-json: '[{"name": "GlobalPassword","value": "${{ secrets.GlobalPassword }}","slotSetting": false},{"name": "SimulatedFailureChance","value": "${{ secrets.SimulatedFailureChance }}","slotSetting": false}]'
        app-settings-json: '[{"name": "GlobalPassword","value": "${{ steps.getSecretsFromTestKeyVault.outputs.GlobalPassword }}","slotSetting": false},{"name": "SimulatedFailureChance","value": "${{ steps.getSecretsFromTestKeyVault.outputs.SimulatedFailureChance }}","slotSetting": false}]'


  release-to-prod-env:
    runs-on: ubuntu-latest

    needs: [ release-to-dev ]

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    env:
      PROD_RESOURCE_GROUP_NAME: DevOpsGitHub-2022-09-08-team-02-prod
      PROD_KEY_VAULT_NAME: kv-prod-aueast-azsprints
      PROD_WEB_APP_NAME: wa-prod-aueast-azsprintseries
      PROD_APP_SERVICE_PLAN_NAME: plan-prod-aueast-azsprintseries

    steps:
      - name: Download the bicep-template artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: bicep-template
          #name: deploy.bicep
          #path: ./deploy.bicep/
          path: ./bicep-template/

      - name: Login to Azure using the Production SP credentials
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AnimalAdoptionServicePrincipal_Prod }}

      - name: Deploy resources to the Test Resource Group using an Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AG_SUBSCRIPTION_GUID }}
          resourceGroupName: ${{ env.PROD_RESOURCE_GROUP_NAME }}
          template: ./bicep-template/deploy.bicep
          parameters: tenantGuid=${{ secrets.AG_TENANT_GUID }} appServicePlanName=${{ env.PROD_APP_SERVICE_PLAN_NAME }} keyVaultName=${{ env.PROD_KEY_VAULT_NAME }} webAppName=${{ env.PROD_WEB_APP_NAME }} resourceGroupServicePrincipalManagedApplicationObjectId=${{ secrets.GHA_MSAG_RG_PROD_AUEAST_AZSPRINTSERIES_SP_MANAGED_APP_OBJECT_ID }}
          failOnStdErr: false

      - name: Download the TAA web portal artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: drop
          path: ./taa-portal/
      - name: Deploy the TAA portal to the Production Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PROD_WEB_APP_NAME }}
          package: ./taa-portal/

      - name: Get Secrets from the Production Key Vault
        id: getSecretsFromProductionKeyVault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.PROD_KEY_VAULT_NAME }}
          secrets: 'GlobalPassword, SimulatedFailureChance'

      - name: Update the App Settings for the Production Web App
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.PROD_WEB_APP_NAME }}
          app-settings-json: '[{"name": "GlobalPassword","value": "${{ steps.getSecretsFromProductionKeyVault.outputs.GlobalPassword }}","slotSetting": false},{"name": "SimulatedFailureChance","value": "${{ steps.getSecretsFromProductionKeyVault.outputs.SimulatedFailureChance }}","slotSetting": false}]'
#comment
