name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Install dependencies for all projects
      run: dotnet restore
      
    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: Publish portal project in Release mode
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --configuration Release --no-build --output ./taa-portal/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: drop
        path:  ${{ github.workspace }}/taa-portal/
        if-no-files-found: error
  release-to-dev:
    runs-on: ubuntu-latest
    
    needs: [ build ]
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: drop
        path: ./taa-portal/
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: AnimalAdoptionApp
        publish-profile: ${{ secrets.AnimalAdoptionAppPublishSettings }}
        package: ./taa-portal/

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AnimalAdoptionServicePrincipal }}

    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: AnimalAdoptionApp
        app-settings-json: '[{"name": "GlobalPassword","value": "${{ secrets.GlobalPassword }}","slotSetting": false},{"name": "SimulatedFailureChance","value": "${{ secrets.SimulatedFailureChance }}","slotSetting": false}]'
